#!/bin/bash
#SBATCH --job-name=dissect_exp
#SBATCH --partition=msfea-ai

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu
#SBATCH --mem=12000
#SBATCH --time=0-05:00:00
##SBATCH --array=1-3%1

## set the environment modules
module load python/base/miniconda3
module load cuda
source /apps/sw/miniconda/etc/profile.d/conda.sh
conda activate myenv

## add my modules
export PYTHONPATH=$HOME/scratch/dissect
export PYTHONPATH=$PYTHONPATH:$HOME/scratch/dissect/experiment

## SWAV + SUPERVISED
python3 gEnsemble.py --models "swav_resnet50|supervised_resnet50" --device "cuda:0" --imagenet "/home/amm90/scratch/imagenet"

